<a href="https://colab.research.google.com/github/SumatiRahate/Sumati-EDS/blob/main/ass3_Matrix_using_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import csv
import numpy as np

filename = "/content/marks1.csv"
data = []

with open(filename, "r") as file:
    csv_reader = csv.reader(file)
    next(csv_reader)

    for row in csv_reader:
        data.append(row[1:])

matrix = np.array(data, dtype=int)

print("Matrix of marks for each student:")
print(matrix)



#Mean of every subject marks
mean = np.mean(matrix, axis=0)
print("Maths  Physics  Chemistry Biology :")
print(mean)



#Totyal marks of each student
row_sum = np.sum(matrix, axis=1)
print("Total marks of each student:")
print(row_sum)


# dividing matrix for each roll no

matrix_301 = matrix[:1, :]

print("301:")
print(matrix_301)


matrix_302 = matrix[1:2, :]

print("302:")
print(matrix_302)


matrix_303 = matrix[2:3, :]

print("303:")
print(matrix_303)


matrix_304 = matrix[3:4, :]

print("304:")
print(matrix_304)



#stacking
#horizantal staking
re_array=np.hstack((matrix_301,matrix_302))
print("Horizantal staked matrix is:")
print(re_array)

#vertical staking 1
arr_301_302=np.vstack((matrix_301,matrix_302))
print("Vertical staked matrix 1 is:")
print(arr_301_302)

#vertical staking 2
arr_303_304=np.vstack((matrix_303,matrix_304))
print("Vertical staked matrix 2 is:")
print(arr_303_304)



#Addition of two matrix
addition=arr_301_302+arr_303_304
print("Addition of two matrix")
print(addition)


#Subtraction of two matrix
subtraction=arr_301_302-arr_303_304
print("Subtraction of two matrix")
print(subtraction)

# Multiplication (element-wise)
multiplication = arr_301_302 * arr_303_304
print("Multiplication (element-wise) is:")
print(multiplication)




# Mean along the columns
mean_columns = np.mean(matrix, axis=0)
print("Mean along columns:")
print(mean_columns)

# Mean along the rows
mean_rows = np.mean(matrix, axis=1)
print("Mean along rows:")
print(mean_rows)

# Standard deviation along the columns
std_columns = np.std(matrix, axis=0)
print("Standard deviation along columns:")
print(std_columns)

# Standard deviation along the rows
std_rows = np.std(matrix, axis=1)
print("Standard deviation along rows:")
print(std_rows)

# Minimum value along the columns
min_columns = np.min(matrix, axis=0)
print("Minimum value along columns:")
print(min_columns)

# Minimum value along the rows
min_rows = np.min(matrix, axis=1)
print("Minimum value along rows:")
print(min_rows)

# Maximum value along the columns
max_columns = np.max(matrix, axis=0)
print("Maximum value along columns:")
print(max_columns)

# Maximum value along the rows
max_rows = np.max(matrix, axis=1)
print("Maximum value along rows:")
print(max_rows)

# Sum along the columns
sum_columns = np.sum(matrix, axis=0)
print("Sum along columns:")
print(sum_columns)

# Sum along the rows
sum_rows = np.sum(matrix, axis=1)
print("Sum along rows:")
print(sum_rows)




# Matrix addition
addition = matrix + 50
print("Matrix Addition:")
print(addition)

# Matrix subtraction
subtraction = matrix - 50
print("Matrix Subtraction:")
print(subtraction)


# Matrix multiplication
multi = matrix * 2
print("multiplication:")
print(multi)

# Matrix division
divi= matrix / 2
print(" Division:")
print(divi)


# Bitwise AND operation
bitwise_and = np.bitwise_and(matrix, 10)
print("Bitwise AND:")
print(bitwise_and)

# Bitwise OR operation
bitwise_or = np.bitwise_or(matrix, 10)
print("Bitwise OR:")
print(bitwise_or)

# Bitwise XOR operation
bitwise_xor = np.bitwise_xor(matrix, 10)
print("Bitwise XOR:")
print(bitwise_xor)

# Bitwise NOT operation
bitwise_not = np.bitwise_not(matrix)
print("Bitwise NOT:")
print(bitwise_not)

Matrix of marks for each student:
[[96 70 80 90]
 [90 71 88 97]
 [94 63 82 86]
 [93 74 86 89]
 [80 78 81 96]
 [88 73 79 99]
 [91 66 77 98]
 [92 65 84 92]
 [85 72 85 93]
 [89 75 90 91]]
Maths  Physics  Chemistry Biology :
[89.8 70.7 83.2 93.1]
Total marks of each student:
[336 346 325 342 335 339 332 333 335 345]
301:
[[96 70 80 90]]
302:
[[90 71 88 97]]
303:
[[94 63 82 86]]
304:
[[93 74 86 89]]
Horizantal staked matrix is:
[[96 70 80 90 90 71 88 97]]
Vertical staked matrix 1 is:
[[96 70 80 90]
 [90 71 88 97]]
Vertical staked matrix 2 is:
[[94 63 82 86]
 [93 74 86 89]]
Addition of two matrix
[[190 133 162 176]
 [183 145 174 186]]
Subtraction of two matrix
[[ 2  7 -2  4]
 [-3 -3  2  8]]
Multiplication (element-wise) is:
[[9024 4410 6560 7740]
 [8370 5254 7568 8633]]
Mean along columns:
[89.8 70.7 83.2 93.1]
Mean along rows:
[84.   86.5  81.25 85.5  83.75 84.75 83.   83.25 83.75 86.25]
Standard deviation along columns:
[4.42266888 4.5177428  3.91918359 4.0607881 ]
Standard deviation along

In [ ]:
import numpy as np
array1=np.array(re_array)
print(array1)

#Copy the array
copied_array = array1.copy()

# View the array
view_array = array1.view()

# Modify the copied array
copied_array[0] = 10

# Modify the view array
view_array[0] = 20

# Print the original array
print("Original Array:")
print(array1)

# Print the copied array
print("Copied Array:")
print(copied_array)

# Print the view array
print("View Array:")
print(view_array)


[[96 70 80 90 90 71 88 97]]
Original Array:
[[20 20 20 20 20 20 20 20]]
Copied Array:
[[10 10 10 10 10 10 10 10]]
View Array:
[[20 20 20 20 20 20 20 20]]


In [ ]:
# Vertical stacking
vertical_stack = np.vstack((array1, copied_array))
print("Vertical Stack:")
print(vertical_stack)

# Horizontal stacking
horizontal_stack = np.hstack((array1, copied_array))
print("Horizontal Stack:")
print(horizontal_stack)

#searching

target = 71
print("\n searching")
if target in array1:
    print(f"The target element {target} is found in the array.")
else:
    print("The target element is not found in the array.")

# Sorting
sorted_arr = sorted(array1)
print("\nSorting:")
print("Original Array:", array1)
print("Sorted Array:", sorted_arr)

# Counting
count = len(array1)
print("\nCounting:")
print(f"The array contains {count} elements.")

Vertical Stack:
[[96 70 80 90 90 71 88 97]
 [10 10 10 10 10 10 10 10]]
Horizontal Stack:
[[96 70 80 90 90 71 88 97 10 10 10 10 10 10 10 10]]

 searching
The target element 71 is found in the array.

Sorting:
Original Array: [[96 70 80 90 90 71 88 97]]
Sorted Array: [array([96, 70, 80, 90, 90, 71, 88, 97])]

Counting:
The array contains 1 elements.
